export const CHANGE_MENU = 'CHANGE_MENU';
export const NOTIFICATION_ADD = 'NOTIFICATION_ADD';
export const PROFILE_CREATE = 'PROFILE_CREATE';
export const PROFILE_UPDATE_SETTINGS = 'PROFILE_UPDATE_SETTINGS';
export const PROFILE_REMOVE = 'PROFILE_REMOVE';
export const PROFILE_SET_ENABLED = 'PROFILE_SET_ENABLED';
